package com.underthykilt.poketypes.data.pokemon

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.fail
import org.junit.Test
import java.io.File
import java.net.HttpURLConnection
import java.net.URL

/**
 * Verifies that every PokemonEntry in pokemon.json has a reachable sprite URL.
 * Reads from app/src/main/assets/pokemon.json (generated by test/generate_pokemon_data.py).
 *
 * Run on demand (requires internet):
 *   ./gradlew test --tests "*.SpriteUrlTest"
 */
class SpriteUrlTest {

    @Serializable
    private data class PokemonEntryJson(val id: Int, val name: String, val generation: Int, val types: List<String>)

    @Test
    fun allSpriteUrlsReturn200() {
        val jsonFile = listOf(
            File("src/main/assets/pokemon.json"),
            File("app/src/main/assets/pokemon.json"),
        ).firstOrNull { it.exists() }

        if (jsonFile == null) {
            println("pokemon.json not found; run: python test/generate_pokemon_data.py")
            return
        }

        val entries = Json.decodeFromString<List<PokemonEntryJson>>(jsonFile.readText())
        val failures = mutableListOf<String>()

        entries.forEach { e ->
            val spriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${e.id}.png"
            val typeLabel = e.types.joinToString("/")
            val code = headRequest(spriteUrl)
            val tag = if (code == 200) "OK  " else "FAIL"
            println("[$tag] #${e.id} ${e.name} ($typeLabel)  ->  HTTP $code")
            if (code != 200) {
                failures += "#${e.id} ${e.name} [$typeLabel] -> HTTP $code  $spriteUrl"
            }
        }

        if (failures.isNotEmpty()) {
            fail("\n${failures.size} sprite URL(s) failed:\n${failures.joinToString("\n")}")
        }
    }

    private fun headRequest(url: String): Int = try {
        val conn = URL(url).openConnection() as HttpURLConnection
        conn.requestMethod = "HEAD"
        conn.connectTimeout = 8_000
        conn.readTimeout = 8_000
        conn.instanceFollowRedirects = true
        conn.responseCode.also { conn.disconnect() }
    } catch (e: Exception) {
        -1
    }
}
