package com.underthykilt.poketypes.data.pokemon

import com.underthykilt.poketypes.data.PokemonType
import com.underthykilt.poketypes.data.PokemonType.*

// AUTO-GENERATED by test/generate_pokemon_data.py — do not edit by hand.
internal val POKEMON: Map<Set<PokemonType>, List<PokemonEntry>> = mapOf(

    // BUG
    setOf(BUG) to listOf(
        PokemonEntry(10, "Caterpie", 1), PokemonEntry(11, "Metapod", 1), PokemonEntry(127, "Pinsir", 1),
        PokemonEntry(204, "Pineco", 2), PokemonEntry(265, "Wurmple", 3), PokemonEntry(266, "Silcoon", 3),
        PokemonEntry(268, "Cascoon", 3), PokemonEntry(313, "Volbeat", 3), PokemonEntry(314, "Illumise", 3),
        PokemonEntry(401, "Kricketot", 4), PokemonEntry(402, "Kricketune", 4), PokemonEntry(412, "Burmy", 4),
        PokemonEntry(588, "Karrablast", 5), PokemonEntry(616, "Shelmet", 5), PokemonEntry(617, "Accelgor", 5),
        PokemonEntry(664, "Scatterbug", 6), PokemonEntry(665, "Spewpa", 6), PokemonEntry(736, "Grubbin", 7),
        PokemonEntry(824, "Blipbug", 8), PokemonEntry(917, "Tarountula", 9), PokemonEntry(918, "Spidops", 9),
        PokemonEntry(919, "Nymble", 9), PokemonEntry(953, "Rellor", 9)
    ),

    // DARK
    setOf(DARK) to listOf(
        PokemonEntry(197, "Umbreon", 2), PokemonEntry(261, "Poochyena", 3), PokemonEntry(262, "Mightyena", 3),
        PokemonEntry(359, "Absol", 3), PokemonEntry(491, "Darkrai", 4), PokemonEntry(509, "Purrloin", 5),
        PokemonEntry(510, "Liepard", 5), PokemonEntry(570, "Zorua", 5), PokemonEntry(571, "Zoroark", 5),
        PokemonEntry(827, "Nickit", 8), PokemonEntry(828, "Thievul", 8), PokemonEntry(942, "Maschiff", 9),
        PokemonEntry(943, "Mabosstiff", 9)
    ),

    // DRAGON
    setOf(DRAGON) to listOf(
        PokemonEntry(147, "Dratini", 1), PokemonEntry(148, "Dragonair", 1), PokemonEntry(371, "Bagon", 3),
        PokemonEntry(372, "Shelgon", 3), PokemonEntry(610, "Axew", 5), PokemonEntry(611, "Fraxure", 5),
        PokemonEntry(612, "Haxorus", 5), PokemonEntry(621, "Druddigon", 5), PokemonEntry(704, "Goomy", 6),
        PokemonEntry(705, "Sliggoo", 6), PokemonEntry(706, "Goodra", 6), PokemonEntry(782, "Jangmo-o", 7),
        PokemonEntry(895, "Regidrago", 8)
    ),

    // ELECTRIC
    setOf(ELECTRIC) to listOf(
        PokemonEntry(25, "Pikachu", 1), PokemonEntry(26, "Raichu", 1), PokemonEntry(100, "Voltorb", 1),
        PokemonEntry(101, "Electrode", 1), PokemonEntry(125, "Electabuzz", 1), PokemonEntry(135, "Jolteon", 1),
        PokemonEntry(172, "Pichu", 2), PokemonEntry(179, "Mareep", 2), PokemonEntry(180, "Flaaffy", 2),
        PokemonEntry(181, "Ampharos", 2), PokemonEntry(239, "Elekid", 2), PokemonEntry(243, "Raikou", 2),
        PokemonEntry(309, "Electrike", 3), PokemonEntry(310, "Manectric", 3), PokemonEntry(311, "Plusle", 3),
        PokemonEntry(312, "Minun", 3), PokemonEntry(403, "Shinx", 4), PokemonEntry(404, "Luxio", 4),
        PokemonEntry(405, "Luxray", 4), PokemonEntry(417, "Pachirisu", 4), PokemonEntry(466, "Electivire", 4),
        PokemonEntry(522, "Blitzle", 5), PokemonEntry(523, "Zebstrika", 5), PokemonEntry(602, "Tynamo", 5),
        PokemonEntry(603, "Eelektrik", 5), PokemonEntry(604, "Eelektross", 5), PokemonEntry(796, "Xurkitree", 7),
        PokemonEntry(807, "Zeraora", 7), PokemonEntry(835, "Yamper", 8), PokemonEntry(836, "Boltund", 8),
        PokemonEntry(871, "Pincurchin", 8), PokemonEntry(894, "Regieleki", 8), PokemonEntry(921, "Pawmi", 9),
        PokemonEntry(938, "Tadbulb", 9), PokemonEntry(939, "Bellibolt", 9)
    ),

    // FAIRY
    setOf(FAIRY) to listOf(
        PokemonEntry(35, "Clefairy", 1), PokemonEntry(36, "Clefable", 1), PokemonEntry(173, "Cleffa", 2),
        PokemonEntry(175, "Togepi", 2), PokemonEntry(209, "Snubbull", 2), PokemonEntry(210, "Granbull", 2),
        PokemonEntry(669, "Flabébé", 6), PokemonEntry(670, "Floette", 6), PokemonEntry(671, "Florges", 6),
        PokemonEntry(682, "Spritzee", 6), PokemonEntry(683, "Aromatisse", 6), PokemonEntry(684, "Swirlix", 6),
        PokemonEntry(685, "Slurpuff", 6), PokemonEntry(700, "Sylveon", 6), PokemonEntry(716, "Xerneas", 6),
        PokemonEntry(764, "Comfey", 7), PokemonEntry(868, "Milcery", 8), PokemonEntry(869, "Alcremie", 8),
        PokemonEntry(888, "Zacian", 8), PokemonEntry(926, "Fidough", 9), PokemonEntry(927, "Dachsbun", 9)
    ),

    // FIGHTING
    setOf(FIGHTING) to listOf(
        PokemonEntry(56, "Mankey", 1), PokemonEntry(57, "Primeape", 1), PokemonEntry(66, "Machop", 1),
        PokemonEntry(67, "Machoke", 1), PokemonEntry(68, "Machamp", 1), PokemonEntry(106, "Hitmonlee", 1),
        PokemonEntry(107, "Hitmonchan", 1), PokemonEntry(236, "Tyrogue", 2), PokemonEntry(237, "Hitmontop", 2),
        PokemonEntry(296, "Makuhita", 3), PokemonEntry(297, "Hariyama", 3), PokemonEntry(447, "Riolu", 4),
        PokemonEntry(532, "Timburr", 5), PokemonEntry(533, "Gurdurr", 5), PokemonEntry(534, "Conkeldurr", 5),
        PokemonEntry(538, "Throh", 5), PokemonEntry(539, "Sawk", 5), PokemonEntry(619, "Mienfoo", 5),
        PokemonEntry(620, "Mienshao", 5), PokemonEntry(674, "Pancham", 6), PokemonEntry(739, "Crabrawler", 7),
        PokemonEntry(766, "Passimian", 7), PokemonEntry(852, "Clobbopus", 8), PokemonEntry(853, "Grapploct", 8),
        PokemonEntry(865, "Sirfetch'd", 8), PokemonEntry(870, "Falinks", 8), PokemonEntry(889, "Zamazenta", 8),
        PokemonEntry(891, "Kubfu", 8)
    ),

    // FIRE
    setOf(FIRE) to listOf(
        PokemonEntry(4, "Charmander", 1), PokemonEntry(5, "Charmeleon", 1), PokemonEntry(37, "Vulpix", 1),
        PokemonEntry(38, "Ninetales", 1), PokemonEntry(58, "Growlithe", 1), PokemonEntry(59, "Arcanine", 1),
        PokemonEntry(77, "Ponyta", 1), PokemonEntry(78, "Rapidash", 1), PokemonEntry(126, "Magmar", 1),
        PokemonEntry(136, "Flareon", 1), PokemonEntry(155, "Cyndaquil", 2), PokemonEntry(156, "Quilava", 2),
        PokemonEntry(157, "Typhlosion", 2), PokemonEntry(218, "Slugma", 2), PokemonEntry(240, "Magby", 2),
        PokemonEntry(244, "Entei", 2), PokemonEntry(255, "Torchic", 3), PokemonEntry(324, "Torkoal", 3),
        PokemonEntry(390, "Chimchar", 4), PokemonEntry(467, "Magmortar", 4), PokemonEntry(498, "Tepig", 5),
        PokemonEntry(513, "Pansear", 5), PokemonEntry(514, "Simisear", 5), PokemonEntry(554, "Darumaka", 5),
        PokemonEntry(555, "Darmanitan Standard", 5), PokemonEntry(631, "Heatmor", 5), PokemonEntry(653, "Fennekin", 6),
        PokemonEntry(654, "Braixen", 6), PokemonEntry(725, "Litten", 7), PokemonEntry(726, "Torracat", 7),
        PokemonEntry(813, "Scorbunny", 8), PokemonEntry(814, "Raboot", 8), PokemonEntry(815, "Cinderace", 8),
        PokemonEntry(909, "Fuecoco", 9), PokemonEntry(910, "Crocalor", 9), PokemonEntry(935, "Charcadet", 9)
    ),

    // FLYING
    setOf(FLYING) to listOf(
        PokemonEntry(641, "Tornadus Incarnate", 5), PokemonEntry(821, "Rookidee", 8), PokemonEntry(822, "Corvisquire", 8)
    ),

    // GHOST
    setOf(GHOST) to listOf(
        PokemonEntry(200, "Misdreavus", 2), PokemonEntry(353, "Shuppet", 3), PokemonEntry(354, "Banette", 3),
        PokemonEntry(355, "Duskull", 3), PokemonEntry(356, "Dusclops", 3), PokemonEntry(429, "Mismagius", 4),
        PokemonEntry(477, "Dusknoir", 4), PokemonEntry(562, "Yamask", 5), PokemonEntry(563, "Cofagrigus", 5),
        PokemonEntry(854, "Sinistea", 8), PokemonEntry(855, "Polteageist", 8), PokemonEntry(864, "Cursola", 8),
        PokemonEntry(897, "Spectrier", 8), PokemonEntry(971, "Greavard", 9), PokemonEntry(972, "Houndstone", 9),
        PokemonEntry(999, "Gimmighoul", 9)
    ),

    // GRASS
    setOf(GRASS) to listOf(
        PokemonEntry(114, "Tangela", 1), PokemonEntry(152, "Chikorita", 2), PokemonEntry(153, "Bayleef", 2),
        PokemonEntry(154, "Meganium", 2), PokemonEntry(182, "Bellossom", 2), PokemonEntry(191, "Sunkern", 2),
        PokemonEntry(192, "Sunflora", 2), PokemonEntry(252, "Treecko", 3), PokemonEntry(253, "Grovyle", 3),
        PokemonEntry(254, "Sceptile", 3), PokemonEntry(273, "Seedot", 3), PokemonEntry(285, "Shroomish", 3),
        PokemonEntry(331, "Cacnea", 3), PokemonEntry(387, "Turtwig", 4), PokemonEntry(388, "Grotle", 4),
        PokemonEntry(420, "Cherubi", 4), PokemonEntry(421, "Cherrim", 4), PokemonEntry(455, "Carnivine", 4),
        PokemonEntry(465, "Tangrowth", 4), PokemonEntry(470, "Leafeon", 4), PokemonEntry(492, "Shaymin Land", 4),
        PokemonEntry(495, "Snivy", 5), PokemonEntry(496, "Servine", 5), PokemonEntry(497, "Serperior", 5),
        PokemonEntry(511, "Pansage", 5), PokemonEntry(512, "Simisage", 5), PokemonEntry(548, "Petilil", 5),
        PokemonEntry(549, "Lilligant", 5), PokemonEntry(556, "Maractus", 5), PokemonEntry(650, "Chespin", 6),
        PokemonEntry(651, "Quilladin", 6), PokemonEntry(672, "Skiddo", 6), PokemonEntry(673, "Gogoat", 6),
        PokemonEntry(753, "Fomantis", 7), PokemonEntry(754, "Lurantis", 7), PokemonEntry(761, "Bounsweet", 7),
        PokemonEntry(762, "Steenee", 7), PokemonEntry(763, "Tsareena", 7), PokemonEntry(810, "Grookey", 8),
        PokemonEntry(811, "Thwackey", 8), PokemonEntry(812, "Rillaboom", 8), PokemonEntry(829, "Gossifleur", 8),
        PokemonEntry(830, "Eldegoss", 8), PokemonEntry(906, "Sprigatito", 9), PokemonEntry(907, "Floragato", 9),
        PokemonEntry(951, "Capsakid", 9), PokemonEntry(1017, "Ogerpon", 9)
    ),

    // GROUND
    setOf(GROUND) to listOf(
        PokemonEntry(27, "Sandshrew", 1), PokemonEntry(28, "Sandslash", 1), PokemonEntry(50, "Diglett", 1),
        PokemonEntry(51, "Dugtrio", 1), PokemonEntry(104, "Cubone", 1), PokemonEntry(105, "Marowak", 1),
        PokemonEntry(231, "Phanpy", 2), PokemonEntry(232, "Donphan", 2), PokemonEntry(328, "Trapinch", 3),
        PokemonEntry(383, "Groudon", 3), PokemonEntry(449, "Hippopotas", 4), PokemonEntry(450, "Hippowdon", 4),
        PokemonEntry(529, "Drilbur", 5), PokemonEntry(749, "Mudbray", 7), PokemonEntry(750, "Mudsdale", 7),
        PokemonEntry(843, "Silicobra", 8), PokemonEntry(844, "Sandaconda", 8)
    ),

    // ICE
    setOf(ICE) to listOf(
        PokemonEntry(361, "Snorunt", 3), PokemonEntry(362, "Glalie", 3), PokemonEntry(378, "Regice", 3),
        PokemonEntry(471, "Glaceon", 4), PokemonEntry(582, "Vanillite", 5), PokemonEntry(583, "Vanillish", 5),
        PokemonEntry(584, "Vanilluxe", 5), PokemonEntry(613, "Cubchoo", 5), PokemonEntry(614, "Beartic", 5),
        PokemonEntry(615, "Cryogonal", 5), PokemonEntry(712, "Bergmite", 6), PokemonEntry(713, "Avalugg", 6),
        PokemonEntry(875, "Eiscue Ice", 8), PokemonEntry(896, "Glastrier", 8), PokemonEntry(974, "Cetoddle", 9),
        PokemonEntry(975, "Cetitan", 9)
    ),

    // NORMAL
    setOf(NORMAL) to listOf(
        PokemonEntry(19, "Rattata", 1), PokemonEntry(20, "Raticate", 1), PokemonEntry(52, "Meowth", 1),
        PokemonEntry(53, "Persian", 1), PokemonEntry(108, "Lickitung", 1), PokemonEntry(113, "Chansey", 1),
        PokemonEntry(115, "Kangaskhan", 1), PokemonEntry(128, "Tauros", 1), PokemonEntry(132, "Ditto", 1),
        PokemonEntry(133, "Eevee", 1), PokemonEntry(137, "Porygon", 1), PokemonEntry(143, "Snorlax", 1),
        PokemonEntry(161, "Sentret", 2), PokemonEntry(162, "Furret", 2), PokemonEntry(190, "Aipom", 2),
        PokemonEntry(206, "Dunsparce", 2), PokemonEntry(216, "Teddiursa", 2), PokemonEntry(217, "Ursaring", 2),
        PokemonEntry(233, "Porygon2", 2), PokemonEntry(234, "Stantler", 2), PokemonEntry(235, "Smeargle", 2),
        PokemonEntry(241, "Miltank", 2), PokemonEntry(242, "Blissey", 2), PokemonEntry(263, "Zigzagoon", 3),
        PokemonEntry(264, "Linoone", 3), PokemonEntry(287, "Slakoth", 3), PokemonEntry(288, "Vigoroth", 3),
        PokemonEntry(289, "Slaking", 3), PokemonEntry(293, "Whismur", 3), PokemonEntry(294, "Loudred", 3),
        PokemonEntry(295, "Exploud", 3), PokemonEntry(300, "Skitty", 3), PokemonEntry(301, "Delcatty", 3),
        PokemonEntry(327, "Spinda", 3), PokemonEntry(335, "Zangoose", 3), PokemonEntry(351, "Castform", 3),
        PokemonEntry(352, "Kecleon", 3), PokemonEntry(399, "Bidoof", 4), PokemonEntry(424, "Ambipom", 4),
        PokemonEntry(427, "Buneary", 4), PokemonEntry(428, "Lopunny", 4), PokemonEntry(431, "Glameow", 4),
        PokemonEntry(432, "Purugly", 4), PokemonEntry(440, "Happiny", 4), PokemonEntry(446, "Munchlax", 4),
        PokemonEntry(463, "Lickilicky", 4), PokemonEntry(474, "Porygon-Z", 4), PokemonEntry(486, "Regigigas", 4),
        PokemonEntry(493, "Arceus", 4), PokemonEntry(504, "Patrat", 5), PokemonEntry(505, "Watchog", 5),
        PokemonEntry(506, "Lillipup", 5), PokemonEntry(507, "Herdier", 5), PokemonEntry(508, "Stoutland", 5),
        PokemonEntry(531, "Audino", 5), PokemonEntry(572, "Minccino", 5), PokemonEntry(573, "Cinccino", 5),
        PokemonEntry(626, "Bouffalant", 5), PokemonEntry(659, "Bunnelby", 6), PokemonEntry(676, "Furfrou", 6),
        PokemonEntry(734, "Yungoos", 7), PokemonEntry(735, "Gumshoos", 7), PokemonEntry(772, "Type: Null", 7),
        PokemonEntry(773, "Silvally", 7), PokemonEntry(775, "Komala", 7), PokemonEntry(819, "Skwovet", 8),
        PokemonEntry(820, "Greedent", 8), PokemonEntry(831, "Wooloo", 8), PokemonEntry(832, "Dubwool", 8),
        PokemonEntry(915, "Lechonk", 9), PokemonEntry(916, "Oinkologne Male", 9), PokemonEntry(924, "Tandemaus", 9),
        PokemonEntry(925, "Maushold Family Of Four", 9), PokemonEntry(982, "Dudunsparce Two Segment", 9), PokemonEntry(1024, "Terapagos", 9)
    ),

    // POISON
    setOf(POISON) to listOf(
        PokemonEntry(23, "Ekans", 1), PokemonEntry(24, "Arbok", 1), PokemonEntry(29, "Nidoran♀", 1),
        PokemonEntry(30, "Nidorina", 1), PokemonEntry(32, "Nidoran♂", 1), PokemonEntry(33, "Nidorino", 1),
        PokemonEntry(88, "Grimer", 1), PokemonEntry(89, "Muk", 1), PokemonEntry(109, "Koffing", 1),
        PokemonEntry(110, "Weezing", 1), PokemonEntry(316, "Gulpin", 3), PokemonEntry(317, "Swalot", 3),
        PokemonEntry(336, "Seviper", 3), PokemonEntry(568, "Trubbish", 5), PokemonEntry(569, "Garbodor", 5),
        PokemonEntry(803, "Poipole", 7)
    ),

    // PSYCHIC
    setOf(PSYCHIC) to listOf(
        PokemonEntry(63, "Abra", 1), PokemonEntry(64, "Kadabra", 1), PokemonEntry(65, "Alakazam", 1),
        PokemonEntry(96, "Drowzee", 1), PokemonEntry(97, "Hypno", 1), PokemonEntry(150, "Mewtwo", 1),
        PokemonEntry(151, "Mew", 1), PokemonEntry(196, "Espeon", 2), PokemonEntry(201, "Unown", 2),
        PokemonEntry(202, "Wobbuffet", 2), PokemonEntry(325, "Spoink", 3), PokemonEntry(326, "Grumpig", 3),
        PokemonEntry(358, "Chimecho", 3), PokemonEntry(360, "Wynaut", 3), PokemonEntry(386, "Deoxys Normal", 3),
        PokemonEntry(433, "Chingling", 4), PokemonEntry(480, "Uxie", 4), PokemonEntry(481, "Mesprit", 4),
        PokemonEntry(482, "Azelf", 4), PokemonEntry(488, "Cresselia", 4), PokemonEntry(517, "Munna", 5),
        PokemonEntry(518, "Musharna", 5), PokemonEntry(574, "Gothita", 5), PokemonEntry(575, "Gothorita", 5),
        PokemonEntry(576, "Gothitelle", 5), PokemonEntry(577, "Solosis", 5), PokemonEntry(578, "Duosion", 5),
        PokemonEntry(579, "Reuniclus", 5), PokemonEntry(605, "Elgyem", 5), PokemonEntry(606, "Beheeyem", 5),
        PokemonEntry(677, "Espurr", 6), PokemonEntry(678, "Meowstic Male", 6), PokemonEntry(789, "Cosmog", 7),
        PokemonEntry(790, "Cosmoem", 7), PokemonEntry(800, "Necrozma", 7), PokemonEntry(856, "Hatenna", 8),
        PokemonEntry(857, "Hattrem", 8), PokemonEntry(955, "Flittle", 9), PokemonEntry(956, "Espathra", 9)
    ),

    // ROCK
    setOf(ROCK) to listOf(
        PokemonEntry(185, "Sudowoodo", 2), PokemonEntry(299, "Nosepass", 3), PokemonEntry(377, "Regirock", 3),
        PokemonEntry(408, "Cranidos", 4), PokemonEntry(409, "Rampardos", 4), PokemonEntry(438, "Bonsly", 4),
        PokemonEntry(524, "Roggenrola", 5), PokemonEntry(525, "Boldore", 5), PokemonEntry(526, "Gigalith", 5),
        PokemonEntry(744, "Rockruff", 7), PokemonEntry(745, "Lycanroc Midday", 7), PokemonEntry(837, "Rolycoly", 8),
        PokemonEntry(874, "Stonjourner", 8), PokemonEntry(932, "Nacli", 9), PokemonEntry(933, "Naclstack", 9),
        PokemonEntry(934, "Garganacl", 9), PokemonEntry(950, "Klawf", 9)
    ),

    // STEEL
    setOf(STEEL) to listOf(
        PokemonEntry(379, "Registeel", 3), PokemonEntry(599, "Klink", 5), PokemonEntry(600, "Klang", 5),
        PokemonEntry(601, "Klinklang", 5), PokemonEntry(808, "Meltan", 7), PokemonEntry(809, "Melmetal", 7),
        PokemonEntry(863, "Perrserker", 8), PokemonEntry(878, "Cufant", 8), PokemonEntry(879, "Copperajah", 8),
        PokemonEntry(968, "Orthworm", 9)
    ),

    // WATER
    setOf(WATER) to listOf(
        PokemonEntry(7, "Squirtle", 1), PokemonEntry(8, "Wartortle", 1), PokemonEntry(9, "Blastoise", 1),
        PokemonEntry(54, "Psyduck", 1), PokemonEntry(55, "Golduck", 1), PokemonEntry(60, "Poliwag", 1),
        PokemonEntry(61, "Poliwhirl", 1), PokemonEntry(86, "Seel", 1), PokemonEntry(90, "Shellder", 1),
        PokemonEntry(98, "Krabby", 1), PokemonEntry(99, "Kingler", 1), PokemonEntry(116, "Horsea", 1),
        PokemonEntry(117, "Seadra", 1), PokemonEntry(118, "Goldeen", 1), PokemonEntry(119, "Seaking", 1),
        PokemonEntry(120, "Staryu", 1), PokemonEntry(129, "Magikarp", 1), PokemonEntry(134, "Vaporeon", 1),
        PokemonEntry(158, "Totodile", 2), PokemonEntry(159, "Croconaw", 2), PokemonEntry(160, "Feraligatr", 2),
        PokemonEntry(186, "Politoed", 2), PokemonEntry(223, "Remoraid", 2), PokemonEntry(224, "Octillery", 2),
        PokemonEntry(245, "Suicune", 2), PokemonEntry(258, "Mudkip", 3), PokemonEntry(320, "Wailmer", 3),
        PokemonEntry(321, "Wailord", 3), PokemonEntry(341, "Corphish", 3), PokemonEntry(349, "Feebas", 3),
        PokemonEntry(350, "Milotic", 3), PokemonEntry(366, "Clamperl", 3), PokemonEntry(367, "Huntail", 3),
        PokemonEntry(368, "Gorebyss", 3), PokemonEntry(370, "Luvdisc", 3), PokemonEntry(382, "Kyogre", 3),
        PokemonEntry(393, "Piplup", 4), PokemonEntry(394, "Prinplup", 4), PokemonEntry(418, "Buizel", 4),
        PokemonEntry(419, "Floatzel", 4), PokemonEntry(422, "Shellos", 4), PokemonEntry(456, "Finneon", 4),
        PokemonEntry(457, "Lumineon", 4), PokemonEntry(489, "Phione", 4), PokemonEntry(490, "Manaphy", 4),
        PokemonEntry(501, "Oshawott", 5), PokemonEntry(502, "Dewott", 5), PokemonEntry(503, "Samurott", 5),
        PokemonEntry(515, "Panpour", 5), PokemonEntry(516, "Simipour", 5), PokemonEntry(535, "Tympole", 5),
        PokemonEntry(550, "Basculin Red Striped", 5), PokemonEntry(594, "Alomomola", 5), PokemonEntry(656, "Froakie", 6),
        PokemonEntry(657, "Frogadier", 6), PokemonEntry(692, "Clauncher", 6), PokemonEntry(693, "Clawitzer", 6),
        PokemonEntry(728, "Popplio", 7), PokemonEntry(729, "Brionne", 7), PokemonEntry(746, "Wishiwashi Solo", 7),
        PokemonEntry(771, "Pyukumuku", 7), PokemonEntry(816, "Sobble", 8), PokemonEntry(817, "Drizzile", 8),
        PokemonEntry(818, "Inteleon", 8), PokemonEntry(833, "Chewtle", 8), PokemonEntry(846, "Arrokuda", 8),
        PokemonEntry(847, "Barraskewda", 8), PokemonEntry(912, "Quaxly", 9), PokemonEntry(913, "Quaxwell", 9),
        PokemonEntry(960, "Wiglett", 9), PokemonEntry(961, "Wugtrio", 9), PokemonEntry(963, "Finizen", 9),
        PokemonEntry(964, "Palafin Zero", 9), PokemonEntry(977, "Dondozo", 9)
    ),

    // BUG / DARK
    setOf(BUG, DARK) to listOf(
        PokemonEntry(920, "Lokix", 9)
    ),

    // BUG / ELECTRIC
    setOf(BUG, ELECTRIC) to listOf(
        PokemonEntry(595, "Joltik", 5), PokemonEntry(596, "Galvantula", 5), PokemonEntry(737, "Charjabug", 7),
        PokemonEntry(738, "Vikavolt", 7)
    ),

    // BUG / FAIRY
    setOf(BUG, FAIRY) to listOf(
        PokemonEntry(742, "Cutiefly", 7), PokemonEntry(743, "Ribombee", 7)
    ),

    // BUG / FIGHTING
    setOf(BUG, FIGHTING) to listOf(
        PokemonEntry(214, "Heracross", 2), PokemonEntry(794, "Buzzwole", 7), PokemonEntry(795, "Pheromosa", 7),
        PokemonEntry(988, "Slither Wing", 9)
    ),

    // BUG / FIRE
    setOf(BUG, FIRE) to listOf(
        PokemonEntry(636, "Larvesta", 5), PokemonEntry(637, "Volcarona", 5), PokemonEntry(850, "Sizzlipede", 8),
        PokemonEntry(851, "Centiskorch", 8)
    ),

    // BUG / FLYING
    setOf(BUG, FLYING) to listOf(
        PokemonEntry(12, "Butterfree", 1), PokemonEntry(123, "Scyther", 1), PokemonEntry(165, "Ledyba", 2),
        PokemonEntry(166, "Ledian", 2), PokemonEntry(193, "Yanma", 2), PokemonEntry(267, "Beautifly", 3),
        PokemonEntry(284, "Masquerain", 3), PokemonEntry(291, "Ninjask", 3), PokemonEntry(414, "Mothim", 4),
        PokemonEntry(415, "Combee", 4), PokemonEntry(416, "Vespiquen", 4), PokemonEntry(469, "Yanmega", 4),
        PokemonEntry(666, "Vivillon", 6)
    ),

    // BUG / GHOST
    setOf(BUG, GHOST) to listOf(
        PokemonEntry(292, "Shedinja", 3)
    ),

    // BUG / GRASS
    setOf(BUG, GRASS) to listOf(
        PokemonEntry(46, "Paras", 1), PokemonEntry(47, "Parasect", 1), PokemonEntry(413, "Wormadam Plant", 4),
        PokemonEntry(540, "Sewaddle", 5), PokemonEntry(541, "Swadloon", 5), PokemonEntry(542, "Leavanny", 5)
    ),

    // BUG / GROUND
    setOf(BUG, GROUND) to listOf(
        PokemonEntry(290, "Nincada", 3)
    ),

    // BUG / ICE
    setOf(BUG, ICE) to listOf(
        PokemonEntry(872, "Snom", 8), PokemonEntry(873, "Frosmoth", 8)
    ),

    // BUG / POISON
    setOf(BUG, POISON) to listOf(
        PokemonEntry(13, "Weedle", 1), PokemonEntry(14, "Kakuna", 1), PokemonEntry(15, "Beedrill", 1),
        PokemonEntry(48, "Venonat", 1), PokemonEntry(49, "Venomoth", 1), PokemonEntry(167, "Spinarak", 2),
        PokemonEntry(168, "Ariados", 2), PokemonEntry(269, "Dustox", 3), PokemonEntry(451, "Skorupi", 4),
        PokemonEntry(543, "Venipede", 5), PokemonEntry(544, "Whirlipede", 5), PokemonEntry(545, "Scolipede", 5)
    ),

    // BUG / PSYCHIC
    setOf(BUG, PSYCHIC) to listOf(
        PokemonEntry(825, "Dottler", 8), PokemonEntry(826, "Orbeetle", 8), PokemonEntry(954, "Rabsca", 9)
    ),

    // BUG / ROCK
    setOf(BUG, ROCK) to listOf(
        PokemonEntry(213, "Shuckle", 2), PokemonEntry(347, "Anorith", 3), PokemonEntry(348, "Armaldo", 3),
        PokemonEntry(557, "Dwebble", 5), PokemonEntry(558, "Crustle", 5), PokemonEntry(900, "Kleavor", 8)
    ),

    // BUG / STEEL
    setOf(BUG, STEEL) to listOf(
        PokemonEntry(205, "Forretress", 2), PokemonEntry(212, "Scizor", 2), PokemonEntry(589, "Escavalier", 5),
        PokemonEntry(632, "Durant", 5), PokemonEntry(649, "Genesect", 5)
    ),

    // BUG / WATER
    setOf(BUG, WATER) to listOf(
        PokemonEntry(283, "Surskit", 3), PokemonEntry(751, "Dewpider", 7), PokemonEntry(752, "Araquanid", 7),
        PokemonEntry(767, "Wimpod", 7), PokemonEntry(768, "Golisopod", 7)
    ),

    // DARK / DRAGON
    setOf(DARK, DRAGON) to listOf(
        PokemonEntry(633, "Deino", 5), PokemonEntry(634, "Zweilous", 5), PokemonEntry(635, "Hydreigon", 5),
        PokemonEntry(799, "Guzzlord", 7), PokemonEntry(1005, "Roaring Moon", 9)
    ),

    // DARK / ELECTRIC
    setOf(DARK, ELECTRIC) to listOf(
        PokemonEntry(877, "Morpeko Full Belly", 8)
    ),

    // DARK / FAIRY
    setOf(DARK, FAIRY) to listOf(
        PokemonEntry(859, "Impidimp", 8), PokemonEntry(860, "Morgrem", 8), PokemonEntry(861, "Grimmsnarl", 8)
    ),

    // DARK / FIGHTING
    setOf(DARK, FIGHTING) to listOf(
        PokemonEntry(559, "Scraggy", 5), PokemonEntry(560, "Scrafty", 5), PokemonEntry(675, "Pangoro", 6),
        PokemonEntry(892, "Urshifu Single Strike", 8)
    ),

    // DARK / FIRE
    setOf(DARK, FIRE) to listOf(
        PokemonEntry(228, "Houndour", 2), PokemonEntry(229, "Houndoom", 2), PokemonEntry(727, "Incineroar", 7),
        PokemonEntry(1004, "Chi-Yu", 9)
    ),

    // DARK / FLYING
    setOf(DARK, FLYING) to listOf(
        PokemonEntry(198, "Murkrow", 2), PokemonEntry(430, "Honchkrow", 4), PokemonEntry(629, "Vullaby", 5),
        PokemonEntry(630, "Mandibuzz", 5), PokemonEntry(717, "Yveltal", 6), PokemonEntry(962, "Bombirdier", 9),
        PokemonEntry(993, "Iron Jugulis", 9)
    ),

    // DARK / GHOST
    setOf(DARK, GHOST) to listOf(
        PokemonEntry(302, "Sableye", 3), PokemonEntry(442, "Spiritomb", 4)
    ),

    // DARK / GRASS
    setOf(DARK, GRASS) to listOf(
        PokemonEntry(274, "Nuzleaf", 3), PokemonEntry(275, "Shiftry", 3), PokemonEntry(332, "Cacturne", 3),
        PokemonEntry(893, "Zarude", 8), PokemonEntry(908, "Meowscarada", 9), PokemonEntry(986, "Brute Bonnet", 9),
        PokemonEntry(1001, "Wo-Chien", 9)
    ),

    // DARK / GROUND
    setOf(DARK, GROUND) to listOf(
        PokemonEntry(551, "Sandile", 5), PokemonEntry(552, "Krokorok", 5), PokemonEntry(553, "Krookodile", 5),
        PokemonEntry(1003, "Ting-Lu", 9)
    ),

    // DARK / ICE
    setOf(DARK, ICE) to listOf(
        PokemonEntry(215, "Sneasel", 2), PokemonEntry(461, "Weavile", 4), PokemonEntry(1002, "Chien-Pao", 9)
    ),

    // DARK / NORMAL
    setOf(DARK, NORMAL) to listOf(
        PokemonEntry(862, "Obstagoon", 8)
    ),

    // DARK / POISON
    setOf(DARK, POISON) to listOf(
        PokemonEntry(434, "Stunky", 4), PokemonEntry(435, "Skuntank", 4), PokemonEntry(452, "Drapion", 4),
        PokemonEntry(904, "Overqwil", 8)
    ),

    // DARK / PSYCHIC
    setOf(DARK, PSYCHIC) to listOf(
        PokemonEntry(686, "Inkay", 6), PokemonEntry(687, "Malamar", 6)
    ),

    // DARK / ROCK
    setOf(DARK, ROCK) to listOf(
        PokemonEntry(248, "Tyranitar", 2)
    ),

    // DARK / STEEL
    setOf(DARK, STEEL) to listOf(
        PokemonEntry(624, "Pawniard", 5), PokemonEntry(625, "Bisharp", 5), PokemonEntry(983, "Kingambit", 9)
    ),

    // DARK / WATER
    setOf(DARK, WATER) to listOf(
        PokemonEntry(318, "Carvanha", 3), PokemonEntry(319, "Sharpedo", 3), PokemonEntry(342, "Crawdaunt", 3),
        PokemonEntry(658, "Greninja", 6)
    ),

    // DRAGON / ELECTRIC
    setOf(DRAGON, ELECTRIC) to listOf(
        PokemonEntry(644, "Zekrom", 5), PokemonEntry(880, "Dracozolt", 8), PokemonEntry(1008, "Miraidon", 9),
        PokemonEntry(1021, "Raging Bolt", 9)
    ),

    // DRAGON / FIGHTING
    setOf(DRAGON, FIGHTING) to listOf(
        PokemonEntry(783, "Hakamo-o", 7), PokemonEntry(784, "Kommo-o", 7), PokemonEntry(1007, "Koraidon", 9)
    ),

    // DRAGON / FIRE
    setOf(DRAGON, FIRE) to listOf(
        PokemonEntry(643, "Reshiram", 5), PokemonEntry(776, "Turtonator", 7), PokemonEntry(1020, "Gouging Fire", 9)
    ),

    // DRAGON / FLYING
    setOf(DRAGON, FLYING) to listOf(
        PokemonEntry(149, "Dragonite", 1), PokemonEntry(334, "Altaria", 3), PokemonEntry(373, "Salamence", 3),
        PokemonEntry(384, "Rayquaza", 3), PokemonEntry(714, "Noibat", 6), PokemonEntry(715, "Noivern", 6)
    ),

    // DRAGON / GHOST
    setOf(DRAGON, GHOST) to listOf(
        PokemonEntry(487, "Giratina Altered", 4), PokemonEntry(885, "Dreepy", 8), PokemonEntry(886, "Drakloak", 8),
        PokemonEntry(887, "Dragapult", 8)
    ),

    // DRAGON / GRASS
    setOf(DRAGON, GRASS) to listOf(
        PokemonEntry(840, "Applin", 8), PokemonEntry(841, "Flapple", 8), PokemonEntry(842, "Appletun", 8),
        PokemonEntry(1011, "Dipplin", 9), PokemonEntry(1019, "Hydrapple", 9)
    ),

    // DRAGON / GROUND
    setOf(DRAGON, GROUND) to listOf(
        PokemonEntry(329, "Vibrava", 3), PokemonEntry(330, "Flygon", 3), PokemonEntry(443, "Gible", 4),
        PokemonEntry(444, "Gabite", 4), PokemonEntry(445, "Garchomp", 4), PokemonEntry(718, "Zygarde 50", 6)
    ),

    // DRAGON / ICE
    setOf(DRAGON, ICE) to listOf(
        PokemonEntry(646, "Kyurem", 5), PokemonEntry(996, "Frigibax", 9), PokemonEntry(997, "Arctibax", 9),
        PokemonEntry(998, "Baxcalibur", 9)
    ),

    // DRAGON / NORMAL
    setOf(DRAGON, NORMAL) to listOf(
        PokemonEntry(780, "Drampa", 7), PokemonEntry(967, "Cyclizar", 9)
    ),

    // DRAGON / POISON
    setOf(DRAGON, POISON) to listOf(
        PokemonEntry(691, "Dragalge", 6), PokemonEntry(804, "Naganadel", 7), PokemonEntry(890, "Eternatus", 8)
    ),

    // DRAGON / PSYCHIC
    setOf(DRAGON, PSYCHIC) to listOf(
        PokemonEntry(380, "Latias", 3), PokemonEntry(381, "Latios", 3)
    ),

    // DRAGON / ROCK
    setOf(DRAGON, ROCK) to listOf(
        PokemonEntry(696, "Tyrunt", 6), PokemonEntry(697, "Tyrantrum", 6)
    ),

    // DRAGON / STEEL
    setOf(DRAGON, STEEL) to listOf(
        PokemonEntry(483, "Dialga", 4), PokemonEntry(884, "Duraludon", 8), PokemonEntry(1018, "Archaludon", 9)
    ),

    // DRAGON / WATER
    setOf(DRAGON, WATER) to listOf(
        PokemonEntry(230, "Kingdra", 2), PokemonEntry(484, "Palkia", 4), PokemonEntry(882, "Dracovish", 8),
        PokemonEntry(978, "Tatsugiri Curly", 9), PokemonEntry(1009, "Walking Wake", 9)
    ),

    // ELECTRIC / FAIRY
    setOf(ELECTRIC, FAIRY) to listOf(
        PokemonEntry(702, "Dedenne", 6), PokemonEntry(785, "Tapu Koko", 7)
    ),

    // ELECTRIC / FIGHTING
    setOf(ELECTRIC, FIGHTING) to listOf(
        PokemonEntry(922, "Pawmo", 9), PokemonEntry(923, "Pawmot", 9), PokemonEntry(992, "Iron Hands", 9)
    ),

    // ELECTRIC / FLYING
    setOf(ELECTRIC, FLYING) to listOf(
        PokemonEntry(145, "Zapdos", 1), PokemonEntry(587, "Emolga", 5), PokemonEntry(642, "Thundurus Incarnate", 5),
        PokemonEntry(940, "Wattrel", 9), PokemonEntry(941, "Kilowattrel", 9)
    ),

    // ELECTRIC / GHOST
    setOf(ELECTRIC, GHOST) to listOf(
        PokemonEntry(479, "Rotom", 4)
    ),

    // ELECTRIC / GROUND
    setOf(ELECTRIC, GROUND) to listOf(
        PokemonEntry(618, "Stunfisk", 5), PokemonEntry(989, "Sandy Shocks", 9)
    ),

    // ELECTRIC / ICE
    setOf(ELECTRIC, ICE) to listOf(
        PokemonEntry(881, "Arctozolt", 8)
    ),

    // ELECTRIC / NORMAL
    setOf(ELECTRIC, NORMAL) to listOf(
        PokemonEntry(694, "Helioptile", 6), PokemonEntry(695, "Heliolisk", 6)
    ),

    // ELECTRIC / POISON
    setOf(ELECTRIC, POISON) to listOf(
        PokemonEntry(848, "Toxel", 8), PokemonEntry(849, "Toxtricity Amped", 8)
    ),

    // ELECTRIC / ROCK
    setOf(ELECTRIC, ROCK) to listOf(
        PokemonEntry(995, "Iron Thorns", 9)
    ),

    // ELECTRIC / STEEL
    setOf(ELECTRIC, STEEL) to listOf(
        PokemonEntry(81, "Magnemite", 1), PokemonEntry(82, "Magneton", 1), PokemonEntry(462, "Magnezone", 4),
        PokemonEntry(777, "Togedemaru", 7)
    ),

    // ELECTRIC / WATER
    setOf(ELECTRIC, WATER) to listOf(
        PokemonEntry(170, "Chinchou", 2), PokemonEntry(171, "Lanturn", 2)
    ),

    // FAIRY / FIGHTING
    setOf(FAIRY, FIGHTING) to listOf(
        PokemonEntry(1006, "Iron Valiant", 9)
    ),

    // FAIRY / FLYING
    setOf(FAIRY, FLYING) to listOf(
        PokemonEntry(176, "Togetic", 2), PokemonEntry(468, "Togekiss", 4), PokemonEntry(905, "Enamorus Incarnate", 8)
    ),

    // FAIRY / GHOST
    setOf(FAIRY, GHOST) to listOf(
        PokemonEntry(778, "Mimikyu Disguised", 7), PokemonEntry(987, "Flutter Mane", 9)
    ),

    // FAIRY / GRASS
    setOf(FAIRY, GRASS) to listOf(
        PokemonEntry(546, "Cottonee", 5), PokemonEntry(547, "Whimsicott", 5), PokemonEntry(755, "Morelull", 7),
        PokemonEntry(756, "Shiinotic", 7), PokemonEntry(787, "Tapu Bulu", 7)
    ),

    // FAIRY / NORMAL
    setOf(FAIRY, NORMAL) to listOf(
        PokemonEntry(39, "Jigglypuff", 1), PokemonEntry(40, "Wigglytuff", 1), PokemonEntry(174, "Igglybuff", 2),
        PokemonEntry(298, "Azurill", 3)
    ),

    // FAIRY / POISON
    setOf(FAIRY, POISON) to listOf(
        PokemonEntry(1016, "Fezandipiti", 9)
    ),

    // FAIRY / PSYCHIC
    setOf(FAIRY, PSYCHIC) to listOf(
        PokemonEntry(122, "Mr. Mime", 1), PokemonEntry(280, "Ralts", 3), PokemonEntry(281, "Kirlia", 3),
        PokemonEntry(282, "Gardevoir", 3), PokemonEntry(439, "Mime Jr.", 4), PokemonEntry(786, "Tapu Lele", 7),
        PokemonEntry(858, "Hatterene", 8), PokemonEntry(985, "Scream Tail", 9)
    ),

    // FAIRY / ROCK
    setOf(FAIRY, ROCK) to listOf(
        PokemonEntry(703, "Carbink", 6), PokemonEntry(719, "Diancie", 6)
    ),

    // FAIRY / STEEL
    setOf(FAIRY, STEEL) to listOf(
        PokemonEntry(303, "Mawile", 3), PokemonEntry(707, "Klefki", 6), PokemonEntry(801, "Magearna", 7),
        PokemonEntry(957, "Tinkatink", 9), PokemonEntry(958, "Tinkatuff", 9), PokemonEntry(959, "Tinkaton", 9)
    ),

    // FAIRY / WATER
    setOf(FAIRY, WATER) to listOf(
        PokemonEntry(183, "Marill", 2), PokemonEntry(184, "Azumarill", 2), PokemonEntry(730, "Primarina", 7),
        PokemonEntry(788, "Tapu Fini", 7)
    ),

    // FIGHTING / FIRE
    setOf(FIGHTING, FIRE) to listOf(
        PokemonEntry(256, "Combusken", 3), PokemonEntry(257, "Blaziken", 3), PokemonEntry(391, "Monferno", 4),
        PokemonEntry(392, "Infernape", 4), PokemonEntry(499, "Pignite", 5), PokemonEntry(500, "Emboar", 5)
    ),

    // FIGHTING / FLYING
    setOf(FIGHTING, FLYING) to listOf(
        PokemonEntry(701, "Hawlucha", 6), PokemonEntry(973, "Flamigo", 9)
    ),

    // FIGHTING / GHOST
    setOf(FIGHTING, GHOST) to listOf(
        PokemonEntry(802, "Marshadow", 7), PokemonEntry(979, "Annihilape", 9)
    ),

    // FIGHTING / GRASS
    setOf(FIGHTING, GRASS) to listOf(
        PokemonEntry(286, "Breloom", 3), PokemonEntry(640, "Virizion", 5), PokemonEntry(652, "Chesnaught", 6)
    ),

    // FIGHTING / GROUND
    setOf(FIGHTING, GROUND) to listOf(
        PokemonEntry(984, "Great Tusk", 9)
    ),

    // FIGHTING / ICE
    setOf(FIGHTING, ICE) to listOf(
        PokemonEntry(740, "Crabominable", 7)
    ),

    // FIGHTING / NORMAL
    setOf(FIGHTING, NORMAL) to listOf(
        PokemonEntry(759, "Stufful", 7), PokemonEntry(760, "Bewear", 7)
    ),

    // FIGHTING / POISON
    setOf(FIGHTING, POISON) to listOf(
        PokemonEntry(453, "Croagunk", 4), PokemonEntry(454, "Toxicroak", 4), PokemonEntry(903, "Sneasler", 8),
        PokemonEntry(1014, "Okidogi", 9)
    ),

    // FIGHTING / PSYCHIC
    setOf(FIGHTING, PSYCHIC) to listOf(
        PokemonEntry(307, "Meditite", 3), PokemonEntry(308, "Medicham", 3), PokemonEntry(475, "Gallade", 4)
    ),

    // FIGHTING / ROCK
    setOf(FIGHTING, ROCK) to listOf(
        PokemonEntry(639, "Terrakion", 5)
    ),

    // FIGHTING / STEEL
    setOf(FIGHTING, STEEL) to listOf(
        PokemonEntry(448, "Lucario", 4), PokemonEntry(638, "Cobalion", 5)
    ),

    // FIGHTING / WATER
    setOf(FIGHTING, WATER) to listOf(
        PokemonEntry(62, "Poliwrath", 1), PokemonEntry(647, "Keldeo Ordinary", 5), PokemonEntry(914, "Quaquaval", 9)
    ),

    // FIRE / FLYING
    setOf(FIRE, FLYING) to listOf(
        PokemonEntry(6, "Charizard", 1), PokemonEntry(146, "Moltres", 1), PokemonEntry(250, "Ho-Oh", 2),
        PokemonEntry(662, "Fletchinder", 6), PokemonEntry(663, "Talonflame", 6), PokemonEntry(741, "Oricorio Baile", 7)
    ),

    // FIRE / GHOST
    setOf(FIRE, GHOST) to listOf(
        PokemonEntry(607, "Litwick", 5), PokemonEntry(608, "Lampent", 5), PokemonEntry(609, "Chandelure", 5),
        PokemonEntry(806, "Blacephalon", 7), PokemonEntry(911, "Skeledirge", 9), PokemonEntry(937, "Ceruledge", 9)
    ),

    // FIRE / GRASS
    setOf(FIRE, GRASS) to listOf(
        PokemonEntry(952, "Scovillain", 9)
    ),

    // FIRE / GROUND
    setOf(FIRE, GROUND) to listOf(
        PokemonEntry(322, "Numel", 3), PokemonEntry(323, "Camerupt", 3)
    ),

    // FIRE / NORMAL
    setOf(FIRE, NORMAL) to listOf(
        PokemonEntry(667, "Litleo", 6), PokemonEntry(668, "Pyroar Male", 6)
    ),

    // FIRE / POISON
    setOf(FIRE, POISON) to listOf(
        PokemonEntry(757, "Salandit", 7), PokemonEntry(758, "Salazzle", 7), PokemonEntry(994, "Iron Moth", 9)
    ),

    // FIRE / PSYCHIC
    setOf(FIRE, PSYCHIC) to listOf(
        PokemonEntry(494, "Victini", 5), PokemonEntry(655, "Delphox", 6), PokemonEntry(936, "Armarouge", 9)
    ),

    // FIRE / ROCK
    setOf(FIRE, ROCK) to listOf(
        PokemonEntry(219, "Magcargo", 2), PokemonEntry(838, "Carkol", 8), PokemonEntry(839, "Coalossal", 8)
    ),

    // FIRE / STEEL
    setOf(FIRE, STEEL) to listOf(
        PokemonEntry(485, "Heatran", 4)
    ),

    // FIRE / WATER
    setOf(FIRE, WATER) to listOf(
        PokemonEntry(721, "Volcanion", 6)
    ),

    // FLYING / GHOST
    setOf(FLYING, GHOST) to listOf(
        PokemonEntry(425, "Drifloon", 4), PokemonEntry(426, "Drifblim", 4)
    ),

    // FLYING / GRASS
    setOf(FLYING, GRASS) to listOf(
        PokemonEntry(187, "Hoppip", 2), PokemonEntry(188, "Skiploom", 2), PokemonEntry(189, "Jumpluff", 2),
        PokemonEntry(357, "Tropius", 3), PokemonEntry(722, "Rowlet", 7), PokemonEntry(723, "Dartrix", 7)
    ),

    // FLYING / GROUND
    setOf(FLYING, GROUND) to listOf(
        PokemonEntry(207, "Gligar", 2), PokemonEntry(472, "Gliscor", 4), PokemonEntry(645, "Landorus Incarnate", 5)
    ),

    // FLYING / ICE
    setOf(FLYING, ICE) to listOf(
        PokemonEntry(144, "Articuno", 1), PokemonEntry(225, "Delibird", 2)
    ),

    // FLYING / NORMAL
    setOf(FLYING, NORMAL) to listOf(
        PokemonEntry(16, "Pidgey", 1), PokemonEntry(17, "Pidgeotto", 1), PokemonEntry(18, "Pidgeot", 1),
        PokemonEntry(21, "Spearow", 1), PokemonEntry(22, "Fearow", 1), PokemonEntry(83, "Farfetch'd", 1),
        PokemonEntry(84, "Doduo", 1), PokemonEntry(85, "Dodrio", 1), PokemonEntry(163, "Hoothoot", 2),
        PokemonEntry(164, "Noctowl", 2), PokemonEntry(276, "Taillow", 3), PokemonEntry(277, "Swellow", 3),
        PokemonEntry(333, "Swablu", 3), PokemonEntry(396, "Starly", 4), PokemonEntry(397, "Staravia", 4),
        PokemonEntry(398, "Staraptor", 4), PokemonEntry(441, "Chatot", 4), PokemonEntry(519, "Pidove", 5),
        PokemonEntry(520, "Tranquill", 5), PokemonEntry(521, "Unfezant", 5), PokemonEntry(627, "Rufflet", 5),
        PokemonEntry(628, "Braviary", 5), PokemonEntry(661, "Fletchling", 6), PokemonEntry(731, "Pikipek", 7),
        PokemonEntry(732, "Trumbeak", 7), PokemonEntry(733, "Toucannon", 7), PokemonEntry(931, "Squawkabilly Green Plumage", 9)
    ),

    // FLYING / POISON
    setOf(FLYING, POISON) to listOf(
        PokemonEntry(41, "Zubat", 1), PokemonEntry(42, "Golbat", 1), PokemonEntry(169, "Crobat", 2)
    ),

    // FLYING / PSYCHIC
    setOf(FLYING, PSYCHIC) to listOf(
        PokemonEntry(177, "Natu", 2), PokemonEntry(178, "Xatu", 2), PokemonEntry(249, "Lugia", 2),
        PokemonEntry(527, "Woobat", 5), PokemonEntry(528, "Swoobat", 5), PokemonEntry(561, "Sigilyph", 5)
    ),

    // FLYING / ROCK
    setOf(FLYING, ROCK) to listOf(
        PokemonEntry(142, "Aerodactyl", 1), PokemonEntry(566, "Archen", 5), PokemonEntry(567, "Archeops", 5),
        PokemonEntry(774, "Minior Red Meteor", 7)
    ),

    // FLYING / STEEL
    setOf(FLYING, STEEL) to listOf(
        PokemonEntry(227, "Skarmory", 2), PokemonEntry(797, "Celesteela", 7), PokemonEntry(823, "Corviknight", 8)
    ),

    // FLYING / WATER
    setOf(FLYING, WATER) to listOf(
        PokemonEntry(130, "Gyarados", 1), PokemonEntry(226, "Mantine", 2), PokemonEntry(278, "Wingull", 3),
        PokemonEntry(279, "Pelipper", 3), PokemonEntry(458, "Mantyke", 4), PokemonEntry(580, "Ducklett", 5),
        PokemonEntry(581, "Swanna", 5), PokemonEntry(845, "Cramorant", 8)
    ),

    // GHOST / GRASS
    setOf(GHOST, GRASS) to listOf(
        PokemonEntry(708, "Phantump", 6), PokemonEntry(709, "Trevenant", 6), PokemonEntry(710, "Pumpkaboo Average", 6),
        PokemonEntry(711, "Gourgeist Average", 6), PokemonEntry(724, "Decidueye", 7), PokemonEntry(781, "Dhelmise", 7),
        PokemonEntry(946, "Bramblin", 9), PokemonEntry(947, "Brambleghast", 9), PokemonEntry(1012, "Poltchageist", 9),
        PokemonEntry(1013, "Sinistcha", 9)
    ),

    // GHOST / GROUND
    setOf(GHOST, GROUND) to listOf(
        PokemonEntry(622, "Golett", 5), PokemonEntry(623, "Golurk", 5), PokemonEntry(769, "Sandygast", 7),
        PokemonEntry(770, "Palossand", 7), PokemonEntry(867, "Runerigus", 8)
    ),

    // GHOST / ICE
    setOf(GHOST, ICE) to listOf(
        PokemonEntry(478, "Froslass", 4)
    ),

    // GHOST / POISON
    setOf(GHOST, POISON) to listOf(
        PokemonEntry(92, "Gastly", 1), PokemonEntry(93, "Haunter", 1), PokemonEntry(94, "Gengar", 1),
        PokemonEntry(1025, "Pecharunt", 9)
    ),

    // GHOST / PSYCHIC
    setOf(GHOST, PSYCHIC) to listOf(
        PokemonEntry(720, "Hoopa", 6), PokemonEntry(792, "Lunala", 7)
    ),

    // GHOST / STEEL
    setOf(GHOST, STEEL) to listOf(
        PokemonEntry(679, "Honedge", 6), PokemonEntry(680, "Doublade", 6), PokemonEntry(681, "Aegislash Shield", 6),
        PokemonEntry(1000, "Gholdengo", 9)
    ),

    // GHOST / WATER
    setOf(GHOST, WATER) to listOf(
        PokemonEntry(592, "Frillish Male", 5), PokemonEntry(593, "Jellicent Male", 5), PokemonEntry(902, "Basculegion Male", 8)
    ),

    // GRASS / GROUND
    setOf(GRASS, GROUND) to listOf(
        PokemonEntry(389, "Torterra", 4), PokemonEntry(948, "Toedscool", 9), PokemonEntry(949, "Toedscruel", 9)
    ),

    // GRASS / ICE
    setOf(GRASS, ICE) to listOf(
        PokemonEntry(459, "Snover", 4), PokemonEntry(460, "Abomasnow", 4)
    ),

    // GRASS / NORMAL
    setOf(GRASS, NORMAL) to listOf(
        PokemonEntry(585, "Deerling", 5), PokemonEntry(586, "Sawsbuck", 5), PokemonEntry(928, "Smoliv", 9),
        PokemonEntry(929, "Dolliv", 9), PokemonEntry(930, "Arboliva", 9)
    ),

    // GRASS / POISON
    setOf(GRASS, POISON) to listOf(
        PokemonEntry(1, "Bulbasaur", 1), PokemonEntry(2, "Ivysaur", 1), PokemonEntry(3, "Venusaur", 1),
        PokemonEntry(43, "Oddish", 1), PokemonEntry(44, "Gloom", 1), PokemonEntry(45, "Vileplume", 1),
        PokemonEntry(69, "Bellsprout", 1), PokemonEntry(70, "Weepinbell", 1), PokemonEntry(71, "Victreebel", 1),
        PokemonEntry(315, "Roselia", 3), PokemonEntry(406, "Budew", 4), PokemonEntry(407, "Roserade", 4),
        PokemonEntry(590, "Foongus", 5), PokemonEntry(591, "Amoonguss", 5)
    ),

    // GRASS / PSYCHIC
    setOf(GRASS, PSYCHIC) to listOf(
        PokemonEntry(102, "Exeggcute", 1), PokemonEntry(103, "Exeggutor", 1), PokemonEntry(251, "Celebi", 2),
        PokemonEntry(898, "Calyrex", 8), PokemonEntry(1010, "Iron Leaves", 9)
    ),

    // GRASS / ROCK
    setOf(GRASS, ROCK) to listOf(
        PokemonEntry(345, "Lileep", 3), PokemonEntry(346, "Cradily", 3)
    ),

    // GRASS / STEEL
    setOf(GRASS, STEEL) to listOf(
        PokemonEntry(597, "Ferroseed", 5), PokemonEntry(598, "Ferrothorn", 5), PokemonEntry(798, "Kartana", 7)
    ),

    // GRASS / WATER
    setOf(GRASS, WATER) to listOf(
        PokemonEntry(270, "Lotad", 3), PokemonEntry(271, "Lombre", 3), PokemonEntry(272, "Ludicolo", 3)
    ),

    // GROUND / ICE
    setOf(GROUND, ICE) to listOf(
        PokemonEntry(220, "Swinub", 2), PokemonEntry(221, "Piloswine", 2), PokemonEntry(473, "Mamoswine", 4)
    ),

    // GROUND / NORMAL
    setOf(GROUND, NORMAL) to listOf(
        PokemonEntry(660, "Diggersby", 6), PokemonEntry(901, "Ursaluna", 8)
    ),

    // GROUND / POISON
    setOf(GROUND, POISON) to listOf(
        PokemonEntry(31, "Nidoqueen", 1), PokemonEntry(34, "Nidoking", 1), PokemonEntry(980, "Clodsire", 9)
    ),

    // GROUND / PSYCHIC
    setOf(GROUND, PSYCHIC) to listOf(
        PokemonEntry(343, "Baltoy", 3), PokemonEntry(344, "Claydol", 3)
    ),

    // GROUND / ROCK
    setOf(GROUND, ROCK) to listOf(
        PokemonEntry(74, "Geodude", 1), PokemonEntry(75, "Graveler", 1), PokemonEntry(76, "Golem", 1),
        PokemonEntry(95, "Onix", 1), PokemonEntry(111, "Rhyhorn", 1), PokemonEntry(112, "Rhydon", 1),
        PokemonEntry(246, "Larvitar", 2), PokemonEntry(247, "Pupitar", 2), PokemonEntry(464, "Rhyperior", 4)
    ),

    // GROUND / STEEL
    setOf(GROUND, STEEL) to listOf(
        PokemonEntry(208, "Steelix", 2), PokemonEntry(530, "Excadrill", 5), PokemonEntry(990, "Iron Treads", 9)
    ),

    // GROUND / WATER
    setOf(GROUND, WATER) to listOf(
        PokemonEntry(194, "Wooper", 2), PokemonEntry(195, "Quagsire", 2), PokemonEntry(259, "Marshtomp", 3),
        PokemonEntry(260, "Swampert", 3), PokemonEntry(339, "Barboach", 3), PokemonEntry(340, "Whiscash", 3),
        PokemonEntry(423, "Gastrodon", 4), PokemonEntry(536, "Palpitoad", 5), PokemonEntry(537, "Seismitoad", 5)
    ),

    // ICE / PSYCHIC
    setOf(ICE, PSYCHIC) to listOf(
        PokemonEntry(124, "Jynx", 1), PokemonEntry(238, "Smoochum", 2), PokemonEntry(866, "Mr. Rime", 8)
    ),

    // ICE / ROCK
    setOf(ICE, ROCK) to listOf(
        PokemonEntry(698, "Amaura", 6), PokemonEntry(699, "Aurorus", 6)
    ),

    // ICE / WATER
    setOf(ICE, WATER) to listOf(
        PokemonEntry(87, "Dewgong", 1), PokemonEntry(91, "Cloyster", 1), PokemonEntry(131, "Lapras", 1),
        PokemonEntry(363, "Spheal", 3), PokemonEntry(364, "Sealeo", 3), PokemonEntry(365, "Walrein", 3),
        PokemonEntry(883, "Arctovish", 8), PokemonEntry(991, "Iron Bundle", 9)
    ),

    // NORMAL / POISON
    setOf(NORMAL, POISON) to listOf(
        PokemonEntry(944, "Shroodle", 9), PokemonEntry(945, "Grafaiai", 9)
    ),

    // NORMAL / PSYCHIC
    setOf(NORMAL, PSYCHIC) to listOf(
        PokemonEntry(203, "Girafarig", 2), PokemonEntry(648, "Meloetta Aria", 5), PokemonEntry(765, "Oranguru", 7),
        PokemonEntry(876, "Indeedee Male", 8), PokemonEntry(899, "Wyrdeer", 8), PokemonEntry(981, "Farigiraf", 9)
    ),

    // NORMAL / WATER
    setOf(NORMAL, WATER) to listOf(
        PokemonEntry(400, "Bibarel", 4)
    ),

    // POISON / PSYCHIC
    setOf(POISON, PSYCHIC) to listOf(
        PokemonEntry(1015, "Munkidori", 9)
    ),

    // POISON / ROCK
    setOf(POISON, ROCK) to listOf(
        PokemonEntry(793, "Nihilego", 7), PokemonEntry(969, "Glimmet", 9), PokemonEntry(970, "Glimmora", 9)
    ),

    // POISON / STEEL
    setOf(POISON, STEEL) to listOf(
        PokemonEntry(965, "Varoom", 9), PokemonEntry(966, "Revavroom", 9)
    ),

    // POISON / WATER
    setOf(POISON, WATER) to listOf(
        PokemonEntry(72, "Tentacool", 1), PokemonEntry(73, "Tentacruel", 1), PokemonEntry(211, "Qwilfish", 2),
        PokemonEntry(690, "Skrelp", 6), PokemonEntry(747, "Mareanie", 7), PokemonEntry(748, "Toxapex", 7)
    ),

    // PSYCHIC / ROCK
    setOf(PSYCHIC, ROCK) to listOf(
        PokemonEntry(337, "Lunatone", 3), PokemonEntry(338, "Solrock", 3), PokemonEntry(1022, "Iron Boulder", 9)
    ),

    // PSYCHIC / STEEL
    setOf(PSYCHIC, STEEL) to listOf(
        PokemonEntry(374, "Beldum", 3), PokemonEntry(375, "Metang", 3), PokemonEntry(376, "Metagross", 3),
        PokemonEntry(385, "Jirachi", 3), PokemonEntry(436, "Bronzor", 4), PokemonEntry(437, "Bronzong", 4),
        PokemonEntry(791, "Solgaleo", 7), PokemonEntry(1023, "Iron Crown", 9)
    ),

    // PSYCHIC / WATER
    setOf(PSYCHIC, WATER) to listOf(
        PokemonEntry(79, "Slowpoke", 1), PokemonEntry(80, "Slowbro", 1), PokemonEntry(121, "Starmie", 1),
        PokemonEntry(199, "Slowking", 2), PokemonEntry(779, "Bruxish", 7), PokemonEntry(976, "Veluza", 9)
    ),

    // ROCK / STEEL
    setOf(ROCK, STEEL) to listOf(
        PokemonEntry(304, "Aron", 3), PokemonEntry(305, "Lairon", 3), PokemonEntry(306, "Aggron", 3),
        PokemonEntry(410, "Shieldon", 4), PokemonEntry(411, "Bastiodon", 4), PokemonEntry(476, "Probopass", 4),
        PokemonEntry(805, "Stakataka", 7)
    ),

    // ROCK / WATER
    setOf(ROCK, WATER) to listOf(
        PokemonEntry(138, "Omanyte", 1), PokemonEntry(139, "Omastar", 1), PokemonEntry(140, "Kabuto", 1),
        PokemonEntry(141, "Kabutops", 1), PokemonEntry(222, "Corsola", 2), PokemonEntry(369, "Relicanth", 3),
        PokemonEntry(564, "Tirtouga", 5), PokemonEntry(565, "Carracosta", 5), PokemonEntry(688, "Binacle", 6),
        PokemonEntry(689, "Barbaracle", 6), PokemonEntry(834, "Drednaw", 8)
    ),

    // STEEL / WATER
    setOf(STEEL, WATER) to listOf(
        PokemonEntry(395, "Empoleon", 4)
    ),

)

fun randomPokemonForTypes(vararg types: PokemonType, maxGeneration: Int = 9): PokemonEntry? =
    POKEMON[types.toSet()]
        ?.filter { it.generation <= maxGeneration }
        ?.randomOrNull()

fun hasPokemonForTypes(vararg types: PokemonType, maxGeneration: Int = 9): Boolean =
    POKEMON[types.toSet()]?.any { it.generation <= maxGeneration } == true
